ktor:
    application:
        modules:
            - ru.hram.ApplicationKt.module
    deployment:
        port: 8080
telegram:
    key: "$TELEGRAM_KEY:443566725:"
    group_id: "$TELEGRAM_GROUP_ID:"
database:
    url: "$DATABASE_URL:"
    user: "$DATABASE_USER:"
    password: "$DATABASE_PASSWORD:"
props:
    auth_token: "$AUTH_TOKEN:"